//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class oa_approvalprocess_process
    {
        public long id { get; set; }
        public string processname { get; set; }
        public string processinfo { get; set; }
        public long companyid { get; set; }
        public long creator { get; set; }
        public System.DateTime addtime { get; set; }
        public int status { get; set; }
    }
}
