//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class oa_project_projects
    {
        public long id { get; set; }
        public long staffid { get; set; }
        public string projectname { get; set; }
        public string projectinfo { get; set; }
        public decimal progress { get; set; }
        public int status { get; set; }
        public System.DateTime addtime { get; set; }
        public System.DateTime updatetime { get; set; }
        public long companyid { get; set; }
        public long person_responsibleid { get; set; }
        public System.DateTime expectbegintime { get; set; }
        public System.DateTime realitybegintime { get; set; }
        public System.DateTime expectfinishtime { get; set; }
        public System.DateTime realityfinishtime { get; set; }
    }
}
