//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class oa_userpower_pagemenu
    {
        public long id { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public string image { get; set; }
        public long parentid { get; set; }
        public string remark { get; set; }
        public int ispage { get; set; }
        public long companyid { get; set; }
        public int status { get; set; }
    }
}
