//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA_Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class oadbEntities : DbContext
    {
        public oadbEntities()
            : base("name=oadbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<oa_achievements_achievementsinfo> oa_achievements_achievementsinfo { get; set; }
        public virtual DbSet<oa_achievements_institution> oa_achievements_institution { get; set; }
        public virtual DbSet<oa_approvalprocess_approvalpersons> oa_approvalprocess_approvalpersons { get; set; }
        public virtual DbSet<oa_approvalprocess_process> oa_approvalprocess_process { get; set; }
        public virtual DbSet<oa_member_companys> oa_member_companys { get; set; }
        public virtual DbSet<oa_member_departments> oa_member_departments { get; set; }
        public virtual DbSet<oa_member_dologs> oa_member_dologs { get; set; }
        public virtual DbSet<oa_member_positions> oa_member_positions { get; set; }
        public virtual DbSet<oa_member_staffs> oa_member_staffs { get; set; }
        public virtual DbSet<oa_member_staffsinfos> oa_member_staffsinfos { get; set; }
        public virtual DbSet<oa_member_staffslogins> oa_member_staffslogins { get; set; }
        public virtual DbSet<oa_notice_noticecomment> oa_notice_noticecomment { get; set; }
        public virtual DbSet<oa_notice_noticetype> oa_notice_noticetype { get; set; }
        public virtual DbSet<oa_power_actions> oa_power_actions { get; set; }
        public virtual DbSet<oa_power_ausers> oa_power_ausers { get; set; }
        public virtual DbSet<oa_power_ausersinfos> oa_power_ausersinfos { get; set; }
        public virtual DbSet<oa_power_auserslogins> oa_power_auserslogins { get; set; }
        public virtual DbSet<oa_power_dologs> oa_power_dologs { get; set; }
        public virtual DbSet<oa_power_functions> oa_power_functions { get; set; }
        public virtual DbSet<oa_power_functionsactions> oa_power_functionsactions { get; set; }
        public virtual DbSet<oa_power_powerlogs> oa_power_powerlogs { get; set; }
        public virtual DbSet<oa_power_roles> oa_power_roles { get; set; }
        public virtual DbSet<oa_power_rolesfunctions> oa_power_rolesfunctions { get; set; }
        public virtual DbSet<oa_project_projects> oa_project_projects { get; set; }
        public virtual DbSet<oa_project_projectsstaffs> oa_project_projectsstaffs { get; set; }
        public virtual DbSet<oa_runtinework_memorandums> oa_runtinework_memorandums { get; set; }
        public virtual DbSet<view_oa_member_staffs_staffsinfos> view_oa_member_staffs_staffsinfos { get; set; }
        public virtual DbSet<view_oa_member_departmentstaffnumber> view_oa_member_departmentstaffnumber { get; set; }
        public virtual DbSet<view_oa_member_position> view_oa_member_position { get; set; }
        public virtual DbSet<oa_userpower_functions> oa_userpower_functions { get; set; }
        public virtual DbSet<oa_userpower_functionsactions> oa_userpower_functionsactions { get; set; }
        public virtual DbSet<oa_userpower_pagemenu> oa_userpower_pagemenu { get; set; }
        public virtual DbSet<oa_userpower_positionsfunctions> oa_userpower_positionsfunctions { get; set; }
        public virtual DbSet<oa_userpower_powerlogs> oa_userpower_powerlogs { get; set; }
        public virtual DbSet<oa_member_staffspositions> oa_member_staffspositions { get; set; }
        public virtual DbSet<view_oa_member_staffposition> view_oa_member_staffposition { get; set; }
        public virtual DbSet<view_oa_member_staffinfolist> view_oa_member_staffinfolist { get; set; }
        public virtual DbSet<view_oa_project_projectstafflist> view_oa_project_projectstafflist { get; set; }
        public virtual DbSet<view_oa_project_projectbug> view_oa_project_projectbug { get; set; }
        public virtual DbSet<oa_project_projectsbugs> oa_project_projectsbugs { get; set; }
        public virtual DbSet<view_oa_project_projectbuglist> view_oa_project_projectbuglist { get; set; }
        public virtual DbSet<view_oa_member_staffsidusername> view_oa_member_staffsidusername { get; set; }
        public virtual DbSet<oa_approvalprocess_staffapplyapprovals> oa_approvalprocess_staffapplyapprovals { get; set; }
        public virtual DbSet<oa_approvalprocess_staffapplys> oa_approvalprocess_staffapplys { get; set; }
        public virtual DbSet<oa_approvalprocess_projects> oa_approvalprocess_projects { get; set; }
        public virtual DbSet<oa_approvalprocess_projectprocess> oa_approvalprocess_projectprocess { get; set; }
        public virtual DbSet<view_oa_approvalprocess_projectprocess> view_oa_approvalprocess_projectprocess { get; set; }
        public virtual DbSet<view_oa_approvalprocess_processperson> view_oa_approvalprocess_processperson { get; set; }
        public virtual DbSet<view_oa_approvalprocess_staffapplylist> view_oa_approvalprocess_staffapplylist { get; set; }
        public virtual DbSet<view_oa_approvalprocess_staffapplyapprovallist> view_oa_approvalprocess_staffapplyapprovallist { get; set; }
        public virtual DbSet<view_oa_approvalprocess_staffapplyall> view_oa_approvalprocess_staffapplyall { get; set; }
        public virtual DbSet<view_oa_achievements_achievementinfolist> view_oa_achievements_achievementinfolist { get; set; }
        public virtual DbSet<view_oa_achievements_staffachievementlist> view_oa_achievements_staffachievementlist { get; set; }
        public virtual DbSet<oa_notice_notice> oa_notice_notice { get; set; }
        public virtual DbSet<oa_forum_reply> oa_forum_reply { get; set; }
        public virtual DbSet<oa_forum_section> oa_forum_section { get; set; }
        public virtual DbSet<oa_forum_topic> oa_forum_topic { get; set; }
        public virtual DbSet<view_oa_forum_section> view_oa_forum_section { get; set; }
        public virtual DbSet<view_oa_forum_reply> view_oa_forum_reply { get; set; }
        public virtual DbSet<view_oa_forum_topic> view_oa_forum_topic { get; set; }
        public virtual DbSet<view_oa_notice_notice> view_oa_notice_notice { get; set; }
        public virtual DbSet<view_oa_notice_noticecomment> view_oa_notice_noticecomment { get; set; }
        public virtual DbSet<oa_power_pagemenu> oa_power_pagemenu { get; set; }
        public virtual DbSet<view_oa_member_companylist> view_oa_member_companylist { get; set; }
        public virtual DbSet<view_oa_power_dologlist> view_oa_power_dologlist { get; set; }
        public virtual DbSet<view_oa_power_powerloglist> view_oa_power_powerloglist { get; set; }
        public virtual DbSet<view_oa_power_auserlist> view_oa_power_auserlist { get; set; }
        public virtual DbSet<view_oa_power_rolefunctionlist> view_oa_power_rolefunctionlist { get; set; }
        public virtual DbSet<view_oa_power_functionactionlist> view_oa_power_functionactionlist { get; set; }
        public virtual DbSet<view_oa_member_positionfunctionlist> view_oa_member_positionfunctionlist { get; set; }
        public virtual DbSet<view_oa_userpower_functionactionlist> view_oa_userpower_functionactionlist { get; set; }
        public virtual DbSet<oa_userpower_actions> oa_userpower_actions { get; set; }
    
        public virtual int proc_updateauser(Nullable<long> id, Nullable<long> roleid, string username, string password, string userword, string realname, string qq, string email, string phone, ObjectParameter result, ObjectParameter msg)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(long));
    
            var roleidParameter = roleid.HasValue ?
                new ObjectParameter("roleid", roleid) :
                new ObjectParameter("roleid", typeof(long));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var userwordParameter = userword != null ?
                new ObjectParameter("userword", userword) :
                new ObjectParameter("userword", typeof(string));
    
            var realnameParameter = realname != null ?
                new ObjectParameter("realname", realname) :
                new ObjectParameter("realname", typeof(string));
    
            var qqParameter = qq != null ?
                new ObjectParameter("qq", qq) :
                new ObjectParameter("qq", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_updateauser", idParameter, roleidParameter, usernameParameter, passwordParameter, userwordParameter, realnameParameter, qqParameter, emailParameter, phoneParameter, result, msg);
        }
    
        public virtual int GetNameByCustomerId(string customerId, ObjectParameter contactName)
        {
            var customerIdParameter = customerId != null ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetNameByCustomerId", customerIdParameter, contactName);
        }
    }
}
