//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_oa_approvalprocess_staffapplyall
    {
        public long id { get; set; }
        public long projectid { get; set; }
        public long processid { get; set; }
        public long companyid { get; set; }
        public long projectprocessid { get; set; }
        public long staffid { get; set; }
        public long approvalstaffid { get; set; }
        public long approvalpersonid { get; set; }
        public string applyname { get; set; }
        public int sort { get; set; }
    }
}
