//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_oa_approvalprocess_projectprocess
    {
        public long id { get; set; }
        public long projectid { get; set; }
        public long processid { get; set; }
        public string projectname { get; set; }
        public string projectinfo { get; set; }
        public string processname { get; set; }
        public string processinfo { get; set; }
        public long companyid { get; set; }
        public int status { get; set; }
        public string pathfile { get; set; }
        public string projectprocessname { get; set; }
    }
}
