//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_oa_project_projectbug
    {
        public long id { get; set; }
        public string projectname { get; set; }
        public string title { get; set; }
        public string type { get; set; }
        public int degree { get; set; }
        public string reproducestep { get; set; }
        public string dostep { get; set; }
        public long writer { get; set; }
        public string writerusername { get; set; }
        public long editor { get; set; }
        public string editorusername { get; set; }
        public int status { get; set; }
        public System.DateTime addtime { get; set; }
        public System.DateTime confirmtime { get; set; }
        public System.DateTime solvetime { get; set; }
        public System.DateTime finishtime { get; set; }
        public long projectid { get; set; }
        public long companyid { get; set; }
    }
}
